<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JSdotNet.Project.Guidelines.Docs\JSdotNet.Project.Guidelines.Docs.csproj" />
    <ProjectReference Include="..\..\src\JSdotNet.Project.Guidelines.McpServer\JSdotNet.Project.Guidelines.McpServer.csproj" />
  </ItemGroup>

</Project>
